#include <iostream>
#include <fstream>
#include <sstream>
#include "lexer.h"
#include "parser.h"
#include "compiler.h"
#include "vm.h"
#include "bytecode_io.h"

// ─── helpers ────────────────────────────────────────────────────────────────

static void printUsage(const char* prog) {
    std::cout <<
        "Usage:\n"
        "  " << prog << " compile <source.cvm> <output.cvmb> [--dis]\n"
        "    Compile a .cvm source file to a .cvmb bytecode file.\n"
        "    --dis   Also print a disassembly of the generated bytecode.\n\n"
        "  " << prog << " run <file.cvmb>\n"
        "    Load and execute a pre-compiled .cvmb bytecode file.\n\n"
        "  " << prog << " exec <source.cvm> [--debug]\n"
        "    Compile and immediately execute a .cvm source (old behaviour).\n\n"
        "  " << prog << " [--debug]\n"
        "    Launch the interactive REPL.\n";
}

// Source → Bytecode (shared by 'compile' and 'exec' modes)
static Bytecode compileSource(const std::string& source, bool debugMode) {
    auto tokens   = tokenize(source);
    Parser parser(tokens);
    auto ast      = parser.parse();

    if (debugMode) {
        std::cout << "[DEBUG] Parsed "
                  << ast->statements.size() << " top-level statements.\n";
    }

    Compiler compiler;
    auto bc = compiler.compile(ast.get());

    if (debugMode) {
        std::cout << "[DEBUG] Compiled to "
                  << bc.instructions.size() << " instructions.\n";
        std::cout << "[DEBUG] Variables: ";
        for (auto& v : bc.varTable) std::cout << v << " ";
        std::cout << "\n";
    }

    return bc;
}

// ─── mode: compile ──────────────────────────────────────────────────────────

static int modeCompile(const std::string& srcPath,
                       const std::string& outPath,
                       bool showDis) {
    std::ifstream f(srcPath);
    if (!f.is_open()) {
        std::cerr << "Error: Cannot open source file '" << srcPath << "'\n";
        return 1;
    }
    std::stringstream ss;
    ss << f.rdbuf();

    Bytecode bc;
    try {
        bc = compileSource(ss.str(), false);
    } catch (std::exception& e) {
        std::cerr << "Compile error: " << e.what() << "\n";
        return 1;
    }

    if (showDis) disassemble(bc);

    if (!saveBytecode(bc, outPath)) return 1;

    std::cout << "Bytecode written to '" << outPath << "' ("
              << bc.instructions.size() << " instructions, "
              << bc.varTable.size()     << " variables).\n";
    return 0;
}

// ─── mode: run ──────────────────────────────────────────────────────────────

static int modeRun(const std::string& bcPath) {
    Bytecode bc;
    try {
        bc = loadBytecode(bcPath);
    } catch (std::exception& e) {
        std::cerr << "Load error: " << e.what() << "\n";
        return 1;
    }

    try {
        VM vm;
        vm.execute(bc);
    } catch (std::exception& e) {
        std::cerr << "Runtime error: " << e.what() << "\n";
        return 1;
    }
    return 0;
}

// ─── mode: exec (compile + run in one shot) ─────────────────────────────────

static int modeExec(const std::string& srcPath, bool debugMode) {
    std::ifstream f(srcPath);
    if (!f.is_open()) {
        std::cerr << "Error: Cannot open file '" << srcPath << "'\n";
        return 1;
    }
    std::stringstream ss;
    ss << f.rdbuf();

    try {
        auto bc = compileSource(ss.str(), debugMode);
        VM vm;
        vm.execute(bc);
    } catch (std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }
    return 0;
}

// ─── mode: REPL ─────────────────────────────────────────────────────────────

static int modeREPL(bool debugMode) {
    std::cout << "==============================\n"
              << "  CVM++ Interactive REPL\n"
              << "  Type 'exit' to quit\n"
              << "==============================\n";

    std::string accumulated;
    while (true) {
        std::cout << ">> ";
        std::string line;
        if (!std::getline(std::cin, line)) break;
        if (line == "exit") break;
        if (line.empty()) continue;

        accumulated += line + "\n";

        char last = line.back();
        if (last == ';' || last == '}') {
            try {
                auto bc = compileSource(accumulated, debugMode);
                VM vm;
                vm.execute(bc);
            } catch (std::exception& e) {
                std::cerr << "Error: " << e.what() << "\n";
            }
            accumulated.clear();
        }
    }
    return 0;
}

// ─── entry point ────────────────────────────────────────────────────────────

int main(int argc, char* argv[]) {
    // Collect non-flag arguments and flags separately
    std::vector<std::string> args;
    bool debugMode = false;
    bool showDis   = false;

    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--debug") debugMode = true;
        else if (a == "--dis") showDis = true;
        else args.push_back(a);
    }

    // ── compile <source.cvm> <output.cvmb> [--dis]
    if (!args.empty() && args[0] == "compile") {
        if (args.size() < 3) {
            std::cerr << "Usage: cvm compile <source.cvm> <output.cvmb>\n";
            return 1;
        }
        return modeCompile(args[1], args[2], showDis);
    }

    // ── run <file.cvmb>
    if (!args.empty() && args[0] == "run") {
        if (args.size() < 2) {
            std::cerr << "Usage: cvm run <file.cvmb>\n";
            return 1;
        }
        return modeRun(args[1]);
    }

    // ── exec <source.cvm>  (backward-compatible single-step mode)
    if (!args.empty() && args[0] == "exec") {
        if (args.size() < 2) {
            std::cerr << "Usage: cvm exec <source.cvm>\n";
            return 1;
        }
        return modeExec(args[1], debugMode);
    }

    // ── legacy: cvm <source.cvm>  (no subcommand — old file-run behaviour)
    if (!args.empty() && args[0] != "help") {
        return modeExec(args[0], debugMode);
    }

    // ── help
    if (!args.empty() && args[0] == "help") {
        printUsage(argv[0]);
        return 0;
    }

    // ── REPL (no arguments)
    return modeREPL(debugMode);
}
